name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@master
        with:
          user: msvaz
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Força a Action a ficar VERDE mesmo com esse erro de log
          plugins_errors_fatal: no
          
          # Removemos tudo o que puxa commits (activity e repositories)
          base: header
          
          # Desativação absoluta
          plugin_habits: no
          plugin_habits_from: 0
          plugin_habits_days: 0
          
          # Plugins que você quer manter
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          
          filename: github-metrics.svg
          theme: dark
          config_display: large
          config_timezone: America/Sao_Paulo
          config_padding: 12%
          config_background: "0D1117"
          config_color: "C9D1D9"
          config_border: "1F2937"
          config_icon: "F59E0B"
          config_title: "F59E0B"
          config_subtitle: "9CA3AF"

          output_action: commit
