name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          user: msvaz
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          filename: github-metrics.svg
          plugins_errors_fatal: no
          
          # Removendo 'activity' e 'repositories' da base
          # Isso impede o plugin de tentar ler os commits viciados
          base: header
          
          # Plugins que funcionam (Línguas e Calendário)
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          
          # Forçando o desligamento total do plugin teimoso
          plugin_habits: no
          plugin_habits_from: 0

          # Estética (Amber/Terminal)
          theme: dark
          config_display: large
          config_timezone: America/Sao_Paulo
          config_padding: 12%
          config_background: "0D1117"
          config_color: "C9D1D9"
          config_border: "1F2937"
          config_icon: "F59E0B"
          config_title: "F59E0B"
          config_subtitle: "9CA3AF"

          output_action: commit
