name: Metrics
on:
  schedule:
    - cron: "0 6 * * *" # todo dia
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: msvaz
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # Conteúdo principal
          base: header, activity, repositories
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Terminal / Amber vibe
          theme: dark
          config_display: large
          config_timezone: America/Sao_Paulo
          config_padding: 12%

      # Cores aplicadas
          config_background: "520075"   # Roxo Profundo (Fundo)
          config_title: "F200FF"        # Magenta Neon (Títulos principais)
          config_icon: "F200FF"         # Magenta Neon (Ícones)
          config_color: "D796F2"        # Lilás Claro (Textos e detalhes)
          config_border: "8A00C4"       # Roxo Médio (Bordas e divisórias)
          output_action: commit


