name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
         steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: msvaz
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Se um plugin der erro (como o habits), a action NÃO vai falhar
          plugins_errors_fatal: no
          
          filename: github-metrics.svg
          base: header, activity, repositories
          
          # Plugins
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          
          # Removi o habits daqui, mas o 'plugins_errors_fatal' 
          # vai garantir que aquele erro no log não pare o processo.

          theme: dark
          config_display: large
          config_timezone: America/Sao_Paulo
          config_padding: 12%
          config_background: "0D1117"
          config_color: "C9D1D9"
          config_border: "1F2937"
          config_icon: "F59E0B"
          config_title: "F59E0B"
          config_subtitle: "9CA3AF"

          output_action: commit
